### ISSUE TITLE
Add support for multiple same-type data sources and include in sidebar

### ISSUE THREAD

**Issue by networkglue** [networkglue/networkglue#17]
Add support for, for instance, multiple Cisco ACS data sources and allow mapping to perform automatic synchronization.

**Comment by networkglue** [comment]
Confirm db cascading!

**Comment by beatnik** [comment]
Added unique IDs for all account tables. Changes in Sync modules done. Working on GUI changes.

**Comment by networkglue** [comment]
Code submitted to GitHub repo
